### ISSUE TITLE
Add a AI chatbot

### ISSUE THREAD

**Issue by Shreya111111** [Shreya111111/Linkscrape#18]

**Comment by HavokSahil** [comment]
@Shreya111111 can I work on that? And can you tell what kind of AI chatbot with what functionality to be added?

**Comment by Shreya111111** [comment]
@HavokSahil basic information related to scrapping and tools used for better understanding our website. u can take help of third party chatbot like kommunicate or open ai key ..as u wish

**Comment by Shreya111111** [comment]
@HavokSahil are u interested in working

**Comment by HavokSahil** [comment]
@Shreya111111  sure I am

**Comment by HavokSahil** [comment]
@Shreya111111 i have made the flow for the bot using flowxo

![Screenshot from 2023-12-29 12-46-47](https://github.com/Shreya111111/Linkscrape/assets/87008169/82f8f6c3-295c-41e8-937c-76fce31c8b24)
![Screenshot from 2023-12-29 12-46-36](https://github.com/Shreya111111/Linkscrape/assets/87008169/b449e712-0475-4a45-a7a9-aa02a5388f38)
![Screenshot from 2023-12-29 12-46-21](https://github.com/Shreya111111/Linkscrape/assets/87008169/7e4bbacf-d31c-47a7-8f57-b9be3cd64061)

this is the link for the bot https://fxo.io/m/grid-plum-9646
type `hello` to start the conversation

Problems: I have used openai API key. I don't have the the paid plan so it face limitations in accepting only 2-3 request per minute.

**Comment by Shreya111111** [comment]
can u create a pr for same @HavokSahil for integrating above
